### ISSUE TITLE
OK.with and ~>>, OK.pipe macro?

### ISSUE THREAD

**Issue by bill-mybiz** [CrowdHailer/OK#21]
Wow. I'm using the lib again this morning and I've been noticing that I am using `~>>` operator in tandem with `OK.with` _a lot_. This is super sweet. Like I've said, I use `with` extensively, and as such, the `|>` becomes much less useful for me. But `~>>` gives me piping back _within `with` statements_, and this makes for a _powerfully_ readable happy path. Take the following code block using native `with`:

```
with(
  # We will query off of the current identity
  {:ok, current_identity} <- IbGib.Expression.Supervisor.start_expression(Enum.at(identity_ib_gibs, 0)),

  # Our search for the latest version must be using the credentials of
  # **that** ibgib's identities, i.e. in that timeline.
  {:ok, src} <-
    IbGib.Expression.Supervisor.start_expression(src_ib_gib),
  {:ok, src_ib_gib_info} <- src |> get_info(),
  {:ok, src_ib_gib_identity_ib_gibs} <-
    get_rel8ns(src_ib_gib_info, "identity", [error_on_not_found: true]),

  # Build the query options
  {:ok, query_opts} <-
    build_query_opts_latest(src_ib_gib_identity_ib_gibs, src_ib_gib),

  # Execute the query itself and extract its single result ib^gib
  {:ok, query_result} <-
    current_identity |> query(identity_ib_gibs, query_opts),
  {:ok, query_result_info} <- query_result |> get_info(),
  {:ok, result_ib_gib} <-
    extract_result_ib_gib(query_result_info, src_ib_gib)
) do
  {:ok, result_ib_gib}
else
  error -> default_handle_error(error)
end
```

_I write comments sometimes when I feel the code is not self-documenting enough, and when there are subtleties, e.g. here it is not obvious why I have to use the src's identity (working with branching timelines is tough to reason about!)_

This is where the `~>>` really comes in handy. Here is the refactored code:

```
OK.with do
  # We will query off of the current identity (1st, arbitrarily)
  current_identity <-
    identity_ib_gibs 
    |> Enum.at(0) 
    |> IbGib.Expression.Supervisor.start_expression()

  # Our search for the latest version must be using the credentials of
  # **that** ibgib's identities, i.e. in that timeline.
  src_ib_gib_identity_ib_gibs <- 
    {:ok, src_ib_gib}
    ~>> IbGib.Expression.Supervisor.start_expression()
    ~>> get_info()
    ~>> get_rel8ns("identity", [error_on_not_found: true])

  # Build the query options
  query_opts <-
    build_query_opts_latest(src_ib_gib_identity_ib_gibs, src_ib_gib)

  # Execute the query itself and pull the result_ib_gib out.
  result_ib_gib <-
    {:ok, current_identity} 
    ~>> query(identity_ib_gibs, query_opts)
    ~>> get_info()
    ~>> extract_result_ib_gib(src_ib_gib)

  OK.success result_ib_gib 
else
  reason -> OK.failure handle_ok_error(reason, log: true)
end
```

This is waaaay cleaner, since piping is so powerfully concise and readable, and it's used in combination with the power of the result monad and `OK.with`.

I'm creating this issue because I think it would be useful to have an optional macro for starting the pipe, since I personally think it's good to keep the tuples out of `OK.with`. For example, instead of 

```
result_ib_gib <-
  {:ok, current_identity} 
  ~>> query(identity_ib_gibs, query_opts)
  ~>> get_info()
  ~>> extract_result_ib_gib(src_ib_gib)
```

it could be...

```
result_ib_gib <-
  OK.pipe current_identity
  ~>> query(identity_ib_gibs, query_opts)
  ~>> get_info()
  ~>> extract_result_ib_gib(src_ib_gib)
```

This may be macro overkill though, but I wanted to discuss the possibility. 

Regardless about the macro, I think the combination of `OK.with` and `~>>` is a powerful feature of the lib that you should consider adding to the documentation (or I could if you like the idea). :+1:

**Comment by CrowdHailer** [comment]
is `OK.pipe` not just the same as `OK.success`? could you use that?

First feeling is, it is quite an involved example for the documentation.
I don't know if you blog at all? If you did an option could be write about your usecase, there it would be a good thing the more indepth and involved it got.
Can a link to this README pointing to it, something like. further example combining pipes and with

**Comment by bill-mybiz** [comment]
> is OK.pipe not just the same as OK.success? could you use that?

It would be the same thing as `OK.success`, yes, but that doesn't read very well. The point would be to have syntactic sugar that adds real value to the construct (IMO obviously). Any additional macros in general increase complexity which is bad, but the point of this macro would be to _combat_ the complexity that occurs when injecting the `:ok` tuple in the code.

> First feeling is, it is quite an involved example for the documentation.

I was just giving you feedback about its use in a real, non-trivial scenario. I wouldn't dream of using that particular example actually in the documentation! :smile:

> I don't know if you blog at all? If you did an option could be write about your usecase, there it would be a good thing the more indepth and involved it got.
> Can a link to this README pointing to it, something like. further example combining pipes and with

That's an _excellent_ suggestion! ibGib itself is a "blogging" mechanism, and I use that all of the time! I'll start an `OK` lib ibGib, just as I already have one for [OCaml ibGib](https://www.ibgib.com/ibgib/OCaml%5EF63C887D5FEC8D10A54C6FEECCCFDB74BE7E86AE404778622FE4406A24F7C079).

The UX is less than optimal for reproducing current views of data like "blogs" and "forums", but that _is_ on the roadmap. I'm just extremely slow with javascript and front end things still. But essentially, blogs and forums are basically like a very small rendering subset of ibGib. ibGib is more like Blog + Forum + Pinterest + Twitter + Facebook + GitHub + Big Data Store (akin to Event Sourcing) + more...

Note: The privacy notice on the landing page is extra scary at the moment because I want to ensure people understand that there aren't deletes and that the data is public, among other things. If you read it and want to continue, it will redirect you to the OCaml ibGib, if you have any questions feel free to ask me here or open an issue! (You would be the first :laughing:)

But regardless of my future "blog" ibGib for OK (because it will still be awhile before I get a blog rendering up unless I can find a front end personage), I still think you should consider a small example that mentions the combination of `OK.with` and `~>>` because it's such a powerful mechanism. Something along the lines of 

> ### Advanced Usage: Combining `OK.with` and `~>>`
> 
> `OK.with` and `~>>` can be combined for an extremely powerful yet _simple_ happy path. 
> Consider the previous cart example, but adding some non-trivial validation and authorization steps.
```elixir
OK.with do
  user <-
    OK.pipe user_id
    ~>> validate(:user_id)
    ~>> fetch_user()

  cart <- 
    OK.pipe user
    ~>> fetch_cart()
    ~>> validate(:cart)
    
  saved_order <-
    OK.pipe cart
    ~>> checkout(user)
    ~>> save_order()

  :email_sent <- 
    send_confirmation_email(user, cart, saved_order)

  OK.success saved_order
end
```

> So in this slightly-less-trivial example, you can't just use a pipe the entire way because you need a reference to the user, cart, and order for sending the email. And you want a happy path, because that is idiomatically powerful. The combination of `OK.with` and `~>>` enables you to use have terse, readable happy paths while not foregoing the piping mechanism.

**Comment by bill-mybiz** [comment]
Here is my first stab at an [OK library "blog" ibGib](https://www.ibgib.com/ibgib/OK%5E544CFD6E792C47AC0DEF0BF1B4388D8C152B35E810637AF3C628ABCC188595FD). It's not pretty, but blogging isn't my focus ATM. It should be pretty straight-forward to create a static site generator.

You can actually comment on it (adding pictures, links, or comments really). But remember there aren't any deletes, as it is an append-only mechanism. The internal structure is very much related to git, although it's more abstractly implemented. You can think of the `gib` in the ibGib's ib^gib as being analogous to its (SHA-256) "commit hash". If you have any questions, just let me know. :smile:

**Comment by bill-mybiz** [comment]
All right, I just finished the [OK ibGib](https://www.ibgib.com/ibgib/OK%5E544CFD6E792C47AC0DEF0BF1B4388D8C152B35E810637AF3C628ABCC188595FD). I added the before/after when using the OK library. At the very least, I'm convincing _myself_ how awesome the OK library is. :laughing:

**Comment by CrowdHailer** [comment]
@bill-mybiz thanks for all the time you put into writing your toughs on this issue. I'm not going to add an `OK.pipe` sorry but I think one `OK.success` is the way to keep things explicit.

The advanced example sounds good and I think that you have added that in one of you PRs

**Comment by CrowdHailer** [comment]
closing as i think the last PR tackled many of these comments
