### ISSUE TITLE
Compiler warning for catchall else block

### ISSUE THREAD

**Issue by bill-mybiz** [CrowdHailer/OK#24]
I'm creating this issue per our previous discussion [here](https://github.com/CrowdHailer/OK/pull/20#issuecomment-287045907).

If there is a catchall in the `else` block in `OK.with`, then it creates a compiler warning, e.g.

```
OK.with do
  a <- safe_div(8, 2)
  b <- safe_div(a, 2)
  OK.success a + b
else
  # This creates a compiler warning.
  _reason -> {:error, "catchall fail"}
end
```

This stems from the unconditional addition of a catchall in `OK.with/2`:

```
defmacro with(do: {:__block__, _, normal}, else: exceptional) do
  exceptional_clauses = exceptional ++ (quote do
        reason ->
          {:error, reason}
  end)
...
```

**Comment by CrowdHailer** [comment]
Discussion in forum on the topic https://elixirforum.com/t/avoiding-always-matches-warnings/4303

**Comment by bill-mybiz** [comment]
Yes, I'm following it as well. I considered jumping in and relating to this issue, however I am unsure if it relates. His use case is within a using statement at the def macro level and deciding which function/macro to include, whereas in OK it is inside of a single macro. But I was gonna let the brain churn a bit and see what I think tomorrow (I do less computer things on Sunday, tho I did wake up and start on my deploy at 4am today 😆).

**Comment by bill-mybiz** [comment]
Yeah, I'm just not coming up with any insight from their discussion. Do you see any solutions?

**Comment by CrowdHailer** [comment]
Didn't see anything useful ye

**Comment by CrowdHailer** [comment]
The reason I have not merged the PR is I am thinking of an alternative solution. Not providing a catch all handler in the construct. If a user provides an else clause. Then they should handle all cases. It's eashy enough to add a catch all clause if that is what you need.

**Comment by CrowdHailer** [comment]
Some more thinking

`for` that never modifies errors

```elixir
OK.for do
  a <- fetch(:a)
  b <- fetch(:b)
after
  a + b
end
``` 
This will return the result of a + b in an ok tuple, therefore the result of a for is always a result tuple

and `try` that expects every case to be matched

```elixir
OK.try do
  a <- fetch(:a)
  b <- fetch(:b)
after
  Response.ok(a + b)
rescue
  :not_found ->
    Response.not_found()
  _ ->
     Response.internal_server_error()
end
```

**Comment by CrowdHailer** [comment]
closing as I think the correct behaviour is as described above
