### ISSUE TITLE
Alternative syntax or some sugar

### ISSUE THREAD

**Issue by seivan** [CrowdHailer/OK#29]
Are there any constraints that would make this impossible

Original (This is a modified version from the `README.md`
```elixir
OK.with do
  user <- fetch_user(1)
  cart <- fetch_cart(user)
  order = checkout(cart)
  save_order(order)
else
  :user_not_found ->           # Match on untagged reason
    {:error, :unauthorized}    # Return a literal error tuple
end
```

Compared to some alternative syntax
```elixir
OK.with do
    1 
      |> fetch_user
      |> fetch_cart
      |> checkout
      |> save_order
else
  :user_not_found ->           # Match on untagged reason
    {:error, :unauthorized}    # Return a literal error tuple
end
```

Maybe not using `|>` but something that allows the original piping from Elixir but with happy path until the end. 

To be honest, this is what Elixir should have done from day 1 :-)

**Comment by seivan** [comment]
Ah the ` ~>>` operator does what I want. 👍

**Comment by bill-mybiz** [comment]
@seivan Note that you can also [use the `~>>` inside of `OK.with`](https://hexdocs.pm/ok/OK.html#with/1-combining-ok-with-and), which I do regularly now that I'm aware, e.g. [here](https://github.com/ibgib/ibgib/blob/master/ib_gib_umb/apps/web_gib/lib/web_gib/bus/commanding/ack.ex#L69), [here](https://github.com/ibgib/ibgib/blob/master/ib_gib_umb/apps/ib_gib/lib/ib_gib/common.ex#L40), ...

**Comment by seivan** [comment]
@bill-mybiz Much obliged!
