### ISSUE TITLE
Warnings on new elixir 1.4.0 rc1

### ISSUE THREAD

**Issue by bill-mybiz** [CrowdHailer/OK#3]
I'm checking out the new elixir rc1 ([forum thread](https://elixirforum.com/t/elixir-v1-4-0-rc-0-released/2627), [GitHub link](https://github.com/elixir-lang/elixir/releases/tag/v1.4.0-rc.1)), and I am getting compiler warnings:

```
warning: this clause cannot match because of different types/sizes
```

Code:
```
# function declaration
def plan(identity_ib_gibs, src, opts) do

...

# OK Usage
{:ok, identity_ib_gibs}
~>> PB.plan("[src]", opts)         # <<< warning on this line
~>> PB.add_fork("fork1", dest_ib)  # <<< not on this line
~>> PB.yo
```

The code is executing fine, as I have a bunch of tests, plus this code is already in production. This release has a lot of compiler warnings added, so it looks like it's possibly an assumption that they're doing with the compiler warning and your macro I think?

I'm posting this issue because I wanted to see if you also get these warnings or if it's something specific to me.

**Comment by CrowdHailer** [comment]
I don't know as I have not tried the new release candidate yet. 
Glad that the code is working fine. 
Do let me know if you manage to investigate any further

**Comment by bill-mybiz** [comment]
I just wanted to give you a heads up that your library may be adversely affected with the new release candidate and that you may want to investigate it yourself before it moves out of RC phase! :smile:

**Comment by whitepaperclip** [comment]
What's the difference between this library and the Elixir `with` operator?

**Comment by CrowdHailer** [comment]
With pipelines you don't have to declare variables like in the `with` operator. As this doesn't much relate to this issue chat on the [forum](https://elixirforum.com/t/ok-elegant-error-handling-for-elixir-pipelines-version-1-0-released/1932) for more detail on the differences

**Comment by CrowdHailer** [comment]
I have got round to upgrading to elixir 1.4. All the warnings should not be removed

**Comment by bill-mybiz** [comment]
> All the warnings should not be removed

@CrowdHailer What exactly does this mean? Typo for "now" be removed? Because for me, the warnings are not removed. This isn't one of the numerous warnings for the build of the package. This looks like a warning of a new interpretation of the macro not being able to match up the number of arguments (but I could be wrong).

**Comment by bill-mybiz** [comment]
I just checked and the warnings pop up when you run `mix test` for your lib at `test/ok_test.exs:40 & 59`

**Comment by CrowdHailer** [comment]
can you copy the warning. I think I know the ones you are talking about

**Comment by bill-mybiz** [comment]
This is the one that I get (and your tests as well):
```
warning: this clause cannot match because of different types/sizes
```
And your tests also give one other warning:
```
warning: no clause will ever match
  test/ok_test.exs:59
```

You will see it if you just run `mix test`.

**Comment by CrowdHailer** [comment]
The one about matching clauses happens when values are hard coded.

i.e.
```elixir
case {:ok, :value} do
  {:ok, v} -> # do v
  {:error, reson} -> # report reason
end
```

It knows that the second branch will never be called because the input is always ok.
However these cases are necessary in testing scenarios. 

I don't know if in you code you have a situation like that

**Comment by bill-mybiz** [comment]
[My code](https://github.com/CrowdHailer/OK/issues/3#issue-193780800) is very similar to the usage on the [README](https://github.com/CrowdHailer/OK/blob/master/README.md):

```
  {:ok, file}
  ~>> File.read
  ~>> Poison.decode
  ~>> Dict.fetch(name)
```

So it sounds like what you're saying is that the first two lines of the code is triggering the warning now, since it will never match against the `:error` case:

```
{:ok, file}
  ~>> File.read
```

What do you suggest is the remedy for this?

**Comment by bill-mybiz** [comment]
Using the pipe is one possibility. Perhaps there is a way to pattern match on the incoming `lhs` value in on the OK pipe operator macro? Or maybe an `OK.start/1` function similar to the more recent `OK.try` styles.

(PS That isn't "my" code really...it's from your README on how to use the lib.)

**Comment by bill-mybiz** [comment]
Actually, I'm not sure if that is the cause of the problem after all. I've added some minimal test code and it isn't prompting the warning. I'll have to figure out why the actual code _is_ prompting it.

**Comment by CrowdHailer** [comment]
lols yes. well that README comes from before elixir got so fussy.

If thats not the cause then I am out of ideas

**Comment by bill-mybiz** [comment]
Ok, I have a minimal repro (sheesh):

```
defmodule OKTest do
  import OK, only: :macros

  def double(a) do
    {:ok, 2 * a}
  end
  
  def foo(num) do
    {:ok, num}
    ~>> double() # <<< complains on this line <<<<
    
    {:ok, 1}
    ~>> double() # <<< does NOT complain about this
  end
end


# and in the test.exs
test "OK lib compiler warning test" do
  OKTest.foo(1)
end
```

So for some reason, it only complains when the starting tuple is a variable and not a literal.

**Comment by CrowdHailer** [comment]
Thanks for the reference really nice to seeing it get used.

For your minimal repo I think that it's possible we are coming across an issue with how elixir is inferring types within macros. It might be worth opening a more generic question about variables vs literals in macros somewhere. The forum perhaps although I am not sure what the exact question might be.

**Comment by Zeeker** [comment]
I've just come across this issue after searching for the reason behind this warning for over an hour. Maybe it should be added to the FAQ section?

**Comment by CrowdHailer** [comment]
@Zeeker sounds good I would merge that PR :-)

What macro is currently giving you this problem? `OK.with/1`?

**Comment by Zeeker** [comment]
@CrowdHailer The issue occurred while using the `~>>` operator with a variable, exactly as described in the issue.

**Comment by bill-mybiz** [comment]
@Zeeker I wasn't going to say anything, but I would be remiss if I stayed completely silent since I am partly to "blame" - having contributed extensively to the docs of this lib, as well as (attempted) PRs, issues, etc. I am now in the process of completely removing this lib. I would be weary of incorporating it into your code, as you can already see that even though it is a small library, this issue has already prevailed for almost a year now. This was ample time, with ample prompts from myself, to resolve this issue and others. :frowning_face: 

Again, I wasn't going to say anything, as I'm sure @CrowdHailer has had good reasons for his actions, but I had to counter-balance my role in convincing others to use the lib. There's my 2 cents anyway, FWIW.

**Comment by CrowdHailer** [comment]
Ok. I think I understand, been a while since looked at this issue. And your
saying this issue solved your problem? Certainly if there is a helpful
comment you would wish in the faq I would welcome it

**Comment by CrowdHailer** [comment]
Ok I had not realized there were still problems. For my part I rarely use
pipelines. (Either |> or ~>>) but have made alot of use of OK.with (and now
replacements OK.for and OK.try).

Is the pipe problem not solved by using a normal pipe first

```
Val
|> func1()
~>> func2()
```

**Comment by Zeeker** [comment]
It is, but it displeases my eyes. :D

**Comment by CrowdHailer** [comment]
Or
```elixir
foo1(val)
~>> foo2()
```


The only PR I have not merged on this repo is relating to the else block,
that was instead solved by the introduction of `for` and `try`

**Comment by CrowdHailer** [comment]
This issue should now be fixed. The code changed is [here](https://github.com/CrowdHailer/OK/commit/aa0b1422366aec3c22e3b16b8e57b2606aa55f7c). A new version [1.9.1](https://twitter.com/hex_pm/status/912059969502982144) has been pushed to hex.

@bill-mybiz apologies for not understanding the issue here. As I mentioned the only PR I remember not merging was related to `OK.with`.

@Zeeker Indeed it was a bit displeasing. Do let me know if this patch fixes your issues.

**Comment by Zeeker** [comment]
@CrowdHailer yup, this indeed fixed the issue. 👍

**Comment by CrowdHailer** [comment]
:whale: :tada:
