### ISSUE TITLE
Suggestion: Allow Only Pipes in OK.With

### ISSUE THREAD

**Issue by lauraannwilliams** [CrowdHailer/OK#30]
I really like the organizational structure of the 

```
OK.with do
   stuff <- stuff
else
  match -> error
end
```

For grouping error handling all in one place. However, I find the ```stuff <- stuff``` syntax has me creating temp variables that just exist to pass into the next step.

It'd be nice to have a block without any `<-` segments.

It would turn a method like this:

```elixir
def update(%{id: id, decision: attrs}, _resolution) do
  OK.with do
    decision <- do_get(id)
    Structure.update_decision(decision, attrs)
  else
    "does not exist" = message -> OK.failure(message)
    %{} = changeset -> OK.failure(changeset.errors)
  end
end
```

into this

```elixir
def update(%{id: id, decision: attrs}, _resolution) do
  OK.with do
    {:ok, id} 
    ~>> do_get()
    ~>> Structure.update_decision(attrs)
  else
    "does not exist" = message -> OK.failure(message)
    %{} = changeset -> OK.failure(changeset.errors)
  end
end
```

Perhaps this could be called something like OK.with_pipe

**Comment by CrowdHailer** [comment]
I think it should be possible to do this without needing any new named macro. Looking at your example I think it should work as is. @bill-mybiz is this more or less what you have been doing already?

**Comment by bill-mybiz** [comment]
Absolutely - I'm a big fan of this. The `~>>` operator dovetails beautifully with `OK.with`.

Check out the documentation on hex [here](https://hexdocs.pm/ok/OK.html#with/1-combining-ok-with-and).

Perhaps it should be on the readme as well.

**Comment by lauraannwilliams** [comment]
lol, it was the code in the hexdocs that had me trying this, but I couldn't get it to work. :) 

Unless there is a <- inside the OK.with clause, I always get the following error

```
== Compilation error on file lib/graphql/decision/resolvers/decision.ex ==
** (FunctionClauseError) no function clause matching in OK.with/1
    expanding macro: OK.with/1
    lib/graphql/decision/resolvers/decision.ex:35: GraphQL.Decision.Resolvers.Decision.update/2
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I couldn't find any examples in the docs of only using the pipeline inside OK.with, so I assumed it was not supported.

**Comment by bill-mybiz** [comment]
> lol, it was the code in the hexdocs that had me trying this, but I couldn't get it to work. :)

:laughing: 

> I couldn't find any examples in the docs or in the linked test file (https://github.com/CrowdHailer/OK/blob/master/test/ok_test.exs) of only using the pipeline inside OK.with, so I assumed it was not supported.

After re-reading your question, I realize that you've been talking about only a _single_ pipe statement inside the `OK.with` statement, and wanting to use the `else` block for error handling. That is an interesting idea and I haven't really thought about it. You can actually use a `case` statement, as the one I've just made in the test file:

```elixir
test "single pipe with error handling - case piped" do
  {:ok, 20}
  ~>> safe_div(2)
  ~>> safe_div(0)
  |> case do
       {:ok, answer} -> 
         IO.puts answer
         {:ok, answer}
       {:error, reason} ->  
         IO.puts reason
         {:error, reason}
     end
end
```

(You could also have the `~>>` statement inside the `case` parens if you prefer). 

As for using `OK.with`, I did a little investigating into the AST produced, and it turns out the error statement you're seeing is because a single line does not produce a `__block__` tuple. So there is no match in the pattern match for the `with` macro [here](https://github.com/CrowdHailer/OK/blob/master/lib/ok.ex#L256). I did a quick hack that matched against the bare `normal` arg in `with/2` and this seemed to address it. But it just seems an odd thing to do, since a `with` statement's original intent was to do _multiple_ lines and avoid nested `case` statements. So I think the implementation would just be syntactic sugar to avoid the above `case` statement.

**Comment by CrowdHailer** [comment]
@bill-mybiz Thanks for pointing me in the right direction.

I also had not though of a usecase for a single expression in a with block, I guess it would certainly not have made sense prior to the else clause existing. However I think it is fairly clear cut what the behaviour should be if someone does want to use a single expression, as in this case. 

I have pushed up a [fix](https://github.com/CrowdHailer/OK/commit/4447203116358dc6b913c136c0bf34a442a7d3bf) and this should now work in [1.6.2](https://hex.pm/packages/ok). 

@lauraannwilliams let me know if this now works for you.

:whale:

**Comment by lauraannwilliams** [comment]
Yes, works for me now. Thank you :)

**Comment by lauraannwilliams** [comment]
Note I'm seeing this warning:

"warning: this clause cannot match because of different types/sizes"

on the `~>> Structure.update_decision(attrs)`. line, but my tests still pass :)

**Comment by CrowdHailer** [comment]
Glad its working.

regards the warning, I think that is because your first line is always an ok tuple. I'm probably going to let that remain for the moment. :-)

**Comment by lauraannwilliams** [comment]
Just realized I don't have to start with an ok tuple so warnings are gone :)

**Comment by bill-mybiz** [comment]
> regards the warning, I think that is because your first line is always an ok tuple. I'm probably going to let that remain for the moment. :-)

That is the same warning in #24, though (not) surprisingly I didn't actually state it explicitly! :laughing: I've accumulated quite a few of these warnings, as they occur whenever you have a catchall error clause, e.g. 

```
OK.with do
...
else
  reason -> ...
end
```
There is still PR #25, but for some reason that hasn't been rejected or accepted.

**Comment by CrowdHailer** [comment]
That's not the same issue. But I should revisit #25

**Comment by lauraannwilliams** [comment]
Just a note for anyone: the syntax I ended up with to eliminate the warnings was

```
def update(%{id: id, decision: attrs}, _resolution) do
  OK.with do
    id 
    |> do_get()
    ~>> Structure.update_decision(attrs)
  else
    "does not exist" = message -> OK.failure(message)
    %{} = changeset -> OK.failure(changeset.errors)
  end
end
```

Wrapping the incoming id in an ok clause triggered the because (I think) the system could tell that first `~>>` could never fail.  

Switching to a regular pipe `|>` fixed that, and the fact that it's in a `~>>` pipeline chain  and wrapped in an OK.with still catches all the errors.
