### ISSUE TITLE
Suggestion/Question regarding OK.for after block

### ISSUE THREAD

**Issue by ecly** [CrowdHailer/OK#35]
With the `OK.with do` I really liked how I could have the return block be implicit. Since that this is deprecated now, I've gone over to `OK.for do`, where I now have to make an explicit `after` block every time. Is there any way around this as it means I end up having to store my value such that I can return it, eg:
```
def champions(id, region) do
  OK.for do 
    champions = 
      get_champions(id, region)
      ~>> Enum.take(3)
      |>  Enum.map(fn map -> Map.get(map,"championId") end)
      |>  Enum.map(fn id -> name_from_id(id) end)
  after 
    champions
  end
end
```

Before I could simply end my pipeline with `|> OK.success` and skip the `else` or `after` block, which I thought was neat.

**Comment by CrowdHailer** [comment]
So it was a deliberate choice to use after as a way to separate binding code, from normally executing code. However I know several people liked the implicit return, I will think about it more and `OK.with` is not going to be removed from the library in the near term.

Separate point, I don't think I understand you code above? If your pipeline works it does not need to be wrapped in a for block.

```elixir
def champions(id, region) do
  get_champions(id, region)
  ~>> Enum.take(3)
  |>  Enum.map(fn map -> Map.get(map,"championId") end)
  |>  Enum.map(fn id -> name_from_id(id) end)
end
```

**Comment by ecly** [comment]
Ah, I had just converted the code and I picked an example that didn't make any sense! That one I can make implicit still! But yeah like this one:

```elixir
  def summoner_ids(name, region) do
    OK.for do
      info <- get_summoner(name, region) 
      id = Map.get(info, "id")
      icon_id = Map.get(info, "profileIconId")
    after
      {id, icon_id}
    end
end 
```

But yeah, you already get there idea. I saw the necessary after block more so as an added form of readability, as it's perhaps easier to understand the code for people unfamiliar with the library when they an after block. But thanks for pointing out my mistake, and I definitely see arguments for both making it implicit and explicit. I guess your intention would also be for me to move the id and icon_id matching into the after block then?

**Comment by CrowdHailer** [comment]
The after block has also made `for` easier to implement than `with`. I think there a less ways for it to produce erroneous warning as well. 

If those keys should always be present I would pattern match.

```elixir
def summoner_ids(name, region) do
 OK.for do
   %{"id" => id, "profileIconId" => icon_id} <- get_summoner(name, region) 
 after
   {id, icon_id}
 end
end
```

Also I would rename get_summoner to fetch_summoner. 
I use get_ for functions that return value or nil (maybe type), and fetch_ for functions that return ok/error (result type)

But I have a lot of these rules that are probably my own thing

**Comment by ecly** [comment]
Ah! I had completely forgotten about pattern matching on maps. I like that a lot! Thanks for the tips! I'm still in early stages of learning elixir so very appreciated.

Fetch does seem more intuitive! I'll close this for now. And thanks again!

**Comment by CrowdHailer** [comment]
No problemo :whale:
