### ISSUE TITLE
Add mapM / sequence to OK.

### ISSUE THREAD

**Issue by jpittis** [CrowdHailer/OK#44]
OK's `~>>` operator has been really useful for error handling. However, it causes me frustration when mapping over a list with a function that can cause errors.

```elixir
def parse(input) do
  parse_into_list(input)
  ~>> validate_length(10)
  ~>> Enum.map(&parse_item/1)
end
```

`parse` returns a list of `{:ok, parsed_item}` and `{:error, msg}` but what we really want is either a list of `parsed_item` or a single `{:error, msg}`. In Haskell, this is often what we use `sequence` for.

```elixir
def sequence(li) do
  result = Enum.reduce_while li, [], fn
    {:ok, val}, acc -> {:cont, [val | acc]}
    {:error, _} = err, _acc -> {:halt, err}
  end
  if is_list(result) do Enum.reverse(result) else result end
end
```

`sequence` has type `[m a] -> m [a]` or in OK's case `[Result a] -> Result [a]`.

We can now take our function from before and use `sequence` on it.

```elixir
~>> Enum.map(&parse_item/1) |> sequence
```

This will either return an `{:ok, [parsed_item1, parsed_item2, ...]}` or the first error the map encountered.

We would rarely use `sequence` directly, we'd instead use a function called `mapM` which does the combined map and sequence in one go!

```elixir
def mapM(li, fun) do
  Enum.map(li, fun) |> sequence
end
```

I use `mapM` in chains of error handling when I want to pass the resulting map on to another function with `~>>`.

```elixir
def parse(input) do
  parse_into_list(input)
  ~>> validate_length(10)
  ~>> mapM(&parse_item/1)
  ~>> do_more_stuff_with_a_list_of_parsed_items
end
```

## I want to add `mapM` to the OK library.

- I don't know if the implementation I've written above is the one we'd want.
- I don't know if we want to call the function `mapM` and `sequence` rather than less scary names.
- I would be pleased to open a PR and go through the review process.

**Comment by jpittis** [comment]
I've opened a PR with with tests and doc test examples.

**Comment by CrowdHailer** [comment]
Done in PR #45
