### ISSUE TITLE
can I match the return text from the touple {:error, text} in case of error

### ISSUE THREAD

**Issue by cocodrino** [CrowdHailer/OK#58]
Hi, would be possible write something like this

```elixir
def validate_text(text) when is_bitstring(text), do: {:ok,text}
def validate_text(_text), do: {:error, "not a valid text to translate"}

#and then if I put

#OK block here
some_text <- validate_text("ok I pass")
wrong_text<- validate_text(3)
rescue #match the error touple and extract the text in the block
{:error,text} -> IO.puts(text)  #handle the error
```

so basically I can return my validation text???...hope you can understand the idea...thanks!!!

**Comment by CrowdHailer** [comment]
Sorry I don't really understand the question.

All the information you need to process your error needs to be included in that error.

```elixir
def validate_text(text) when is_bitstring(text), do: {:ok,text}
def validate_text(text), do: {:error, {:invalid_text, text}}
```

**Comment by cocodrino** [comment]
hi @CrowdHailer, but suppose that I've several functions like

```ex

def validate_text(text), do: {:error, {:invalid_text, "not a valid text"}}

def validate_age(age), do: {:error, {:invalid_age, "not a valid age"}}

```

in this code

```ex
require OK
import Raxx

OK.try do
  user <- fetch_user(1)             # `<-` operator means func returns {:ok, user}
  cart <- fetch_cart(1)             # `<-` again, {:ok, cart}
  order = checkout(cart, user)      # `=` allows pattern matching on non-tagged funcs
  saved_order <- save_order(order)
after
  response(:created)                # Value will be returned unwrapped
rescue
  :user_not_found ->
    response(:not_found)
  :could_not_save ->
    response(:internal_server_error)
end
```

you write separate logics for every error, when user is not found produce a different behaviour that when you can save...but what happen if I don't need produce different behaviour just only print the error message: not a valid age or not a valid text

would be possible something like
```exs
rescue
  {_error ,message} ->
    IO.puts(message)  #so I just print the error message for the function that fails.
  
end
```

basically I just need print the error message include in my function...

hope you can understand better my idea now...thank you so much!!!

**Comment by CrowdHailer** [comment]
> would be possible something like

Did you actually try doing exactly what you suggested you wanted. I think it should work
