### ISSUE TITLE
Proposal: add `ok?` and `error?` methods

### ISSUE THREAD

**Issue by cottinisimone** [CrowdHailer/OK#59]
Could be cool to have some other helpers to check if result tuple is in error or ok.

The use case in my mind is filter a collection of result tuples looking only for ok results.

Thank you in advance

**Comment by CrowdHailer** [comment]
Can you add some example code snippets for how you would use the proposed functions.
Sounds interesting

**Comment by thomasnaudin** [comment]
I had the same use case.
I think we could use it this way :

```elixir
{:ok, some_value}
|> OK.is_ok?()                       # returns true

{:error, some_reason}
|> OK.is_ok?()                       # returns false

{:ok, some_value}
|> OK.is_error?()                    # returns false

{:error, some_reason}
|> OK.is_error?()                    # returns true

# Keeps only successes
for result <- results_list, OK.is_ok?(result), do: result

# Keeps only failures
for result <- results_list, OK.is_error?(result), do: result
```

**Comment by CrowdHailer** [comment]
I'm glad you raised the point about `for {:ok, value} <- results_list, do: result`.

My thinking is if I have a list of only `{:ok, value}` I would want that as a list of `value`. A "result" type is only valuable if it can have both option, and in a typed language a list of results would force you to always handle errors that don't exist. 

That said the pipeline example makes more sense, and it's not going to be much to add it to the library. Pr welcome
